

export const formAssets: {label:string, key:string, type:string}[] = [
    { label:"Ticker", key:"ticker", type:"text" },
    { label:"Name", key:"name", type:"text" },
    { label:"Quantity", key:"quantity", type:"number" },
    { label:"Purchase Unit Price", key:"purchaseUnitPrice", type:"number" },
    { label:"Last Price", key:"lastUnitPrice", type:"number" },
    { label:"Currency", key:"currency", type:"text" },
    { label:"Country", key:"country", type:"text" },
    {label:"Purchase Date", key:"purchaseDate", type:"date" },
];

export const typesWithTicker = [
    "stock",
    "bond",
    "mutual_fund",
    "etf",
    "crypto",
    "commodity",
    "forex",
    "precious_metals"
];

export const countries = [
    { code: "US", name: "United States" },
    { code: "CN", name: "China" },
    { code: "JP", name: "Japan" },
    { code: "GB", name: "United Kingdom" },
    { code: "DE", name: "Germany" },
    { code: "FR", name: "France" },
    { code: "IN", name: "India" },
    { code: "CA", name: "Canada" },
    { code: "KR", name: "South Korea" },
    { code: "AU", name: "Australia" },
    { code: "HK", name: "Hong Kong" },
    { code: "SG", name: "Singapore" },
    { code: "CH", name: "Switzerland" },
    { code: "NL", name: "Netherlands" },
    { code: "SE", name: "Sweden" },
    { code: "ES", name: "Spain" },
    { code: "IT", name: "Italy" },
    { code: "BR", name: "Brazil" },
    { code: "MX", name: "Mexico" },
    { code: "RU", name: "Russia" },
    { code: "ZA", name: "South Africa" },
    { code: "TR", name: "Turkey" },
    { code: "BE", name: "Belgium" },
    { code: "NO", name: "Norway" },
    { code: "DK", name: "Denmark" },
    { code: "FI", name: "Finland" },
    { code: "IE", name: "Ireland" },
    { code: "PL", name: "Poland" },
    { code: "AT", name: "Austria" },
    { code: "IL", name: "Israel" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "QA", name: "Qatar" },
    { code: "KR", name: "South Korea" },
    { code: "MY", name: "Malaysia" },
    { code: "TH", name: "Thailand" },
    { code: "ID", name: "Indonesia" },
    { code: "PH", name: "Philippines" },
    { code: "VN", name: "Vietnam" },
    { code: "PK", name: "Pakistan" },
    { code: "EG", name: "Egypt" },
    { code: "NG", name: "Nigeria" },
    { code: "KE", name: "Kenya" },
    { code: "CO", name: "Colombia" },
    { code: "CL", name: "Chile" },
    { code: "AR", name: "Argentina" },
    { code: "PE", name: "Peru" },
    { code: "VN", name: "Vietnam" },
    { code: "TW", name: "Taiwan" },
    { code: "CZ", name: "Czech Republic" },
    { code: "HU", name: "Hungary" },
    { code: "RO", name: "Romania" },
    { code: "GR", name: "Greece" },
    { code: "PT", name: "Portugal" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "HR", name: "Croatia" },
    { code: "RS", name: "Serbia" },
    { code: "BG", name: "Bulgaria" },
    { code: "LT", name: "Lithuania" },
    { code: "LV", name: "Latvia" },
    { code: "EE", name: "Estonia" },
    { code: "UA", name: "Ukraine" },
    { code: "BY", name: "Belarus" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "AM", name: "Armenia" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "GE", name: "Georgia" },
    { code: "MN", name: "Mongolia" },
    { code: "NZ", name: "New Zealand" },
    { code: "FI", name: "Finland" },
    { code: "IE", name: "Ireland" },
    { code: "IS", name: "Iceland" },
    { code: "LU", name: "Luxembourg" },
    { code: "MT", name: "Malta" },
    { code: "CY", name: "Cyprus" },
    { code: "LI", name: "Liechtenstein" },
    { code: "MC", name: "Monaco" },
    { code: "SM", name: "San Marino" },
    { code: "VA", name: "Vatican City" },
    { code: "CO", name: "Costa Rica" },
    { code: "PA", name: "Panama" },
    { code: "UY", name: "Uruguay" },
    { code: "DO", name: "Dominican Republic" },
    { code: "EC", name: "Ecuador" },
    { code: "BO", name: "Bolivia" },
    { code: "PY", name: "Paraguay" },
    { code: "VE", name: "Venezuela" },
    { code: "JM", name: "Jamaica" },
    { code: "TT", name: "Trinidad and Tobago" },
    { code: "BS", name: "Bahamas" },
    { code: "BB", name: "Barbados" },
    { code: "LC", name: "Saint Lucia" },
    { code: "VC", name: "Saint Vincent and the Grenadines" },
    { code: "AG", name: "Antigua and Barbuda" },
    { code: "KN", name: "Saint Kitts and Nevis" },
    { code: "BM", name: "Bermuda" },
    { code: "GU", name: "Guam" },
    { code: "AS", name: "American Samoa" },
    { code: "MP", name: "Northern Mariana Islands" },
    { code: "VI", name: "U.S. Virgin Islands" },
    { code: "PF", name: "French Polynesia" }
];

export const countrySuffixMap: Record<string, string> = {
    "United States": "US",
    "Germany": "DE",
    "Poland": "PL",
    "United Kingdom": "GB",
    "France": "FR",
    "Japan": "JP",
    "China": "CN",
    "Canada": "CA",
    "Switzerland": "CH",
    "India": "IN",
    "Australia": "AU",
    "South Korea": "KR",
    "Hong Kong": "HK",
    "Netherlands": "NL",
    "Spain": "ES",
    "Italy": "IT",
    "Sweden": "SE",
    "Norway": "NO",
    "Denmark": "DK",
    "Finland": "FI",
    "Belgium": "BE",
    "Brazil": "BR",
    "Mexico": "MX",
    "Russia": "RU",
    "South Africa": "ZA",
    "Turkey": "TR",
    "Austria": "AT",
    "Ireland": "IE",
    "Portugal": "PT",
    "Greece": "GR",
    "Czech Republic": "CZ",
    "Hungary": "HU",
};

export const currencies = [
    { value: "USD", label: "USD – US Dollar" },
    { value: "EUR", label: "EUR – Euro" },
    { value: "GBP", label: "GBP – British Pound" },
    { value: "CHF", label: "CHF – Swiss Franc" },
    { value: "JPY", label: "JPY – Japanese Yen" },
    { value: "PLN", label: "PLN – Polish Zloty" },
    { value: "CAD", label: "CAD – Canadian Dollar" },
    { value: "AUD", label: "AUD – Australian Dollar" },
    { value: "CNY", label: "CNY – Chinese Yuan" },
    { value: "NZD", label: "NZD – New Zealand Dollar" },
    { value: "SEK", label: "SEK – Swedish Krona" },
    { value: "NOK", label: "NOK – Norwegian Krone" },
    { value: "MXN", label: "MXN – Mexican Peso" },
    { value: "SGD", label: "SGD – Singapore Dollar" },
    { value: "HKD", label: "HKD – Hong Kong Dollar" },
    { value: "KRW", label: "KRW – South Korean Won" }
];

export const assetTypes = [
    { value: "stock", label: "Stock" },
    { value: "bond", label: "Bond" },
    { value: "mutual_fund", label: "Mutual Fund" },
    { value: "etf", label: "ETF (Exchange-Traded Fund)" },
    { value: "real_estate", label: "Real Estate" },
    { value: "crypto", label: "Cryptocurrency" },
    { value: "commodity", label: "Commodity" },
    { value: "cash", label: "Cash" },
    { value: "private_equity", label: "Private Equity" },
    { value: "hedge_fund", label: "Hedge Fund" },
    { value: "collectibles", label: "Collectibles (Art, Antiques)" },
    { value: "forex", label: "Forex (Foreign Exchange)" },
    { value: "infrastructure", label: "Infrastructure" },
    { value: "venture_capital", label: "Venture Capital" },
    { value: "precious_metals", label: "Precious Metals (Gold, Silver)" },
    { value: "insurance_contracts", label: "Insurance Contracts" },
    { value: "structured_products", label: "Structured Products" },
    { value: "debt_instruments", label: "Debt Instruments" },
    { value: "royalties", label: "Royalties" },
    { value: "other", label: "Other" }
];
