name: Daily Asset Refresh


on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  refresh_assets:
    runs-on: ubuntu-latest

    steps:
      - name: DataStore Refresh API
        run: |
          echo "Refreshing datastore data..."
          status=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://investo-lit9.vercel.app/api/dataStore/refresh)
          if [ "$status" -ne 200 ]; then
            echo "Error occured while refreshing datastore, status: $status"
            exit 1
          fi
          echo "Datastore refreshed."

      - name: Assets Refresh API
        run: |
          echo "Refreshing assets prices..."
          status=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://investo-lit9.vercel.app/api/user/assets/refresh)
          if [ "$status" -ne 200 ]; then
            echo "Error occured while refreshing assets, status: $status"
            exit 1
          fi
          echo "Assety refreshed."

      - name: Create portfolio snapshots
        run: |
          echo "Creating portfolio snapshots..."
          status=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://investo-lit9.vercel.app/api/user/walletSnapshots)
          if [ "$status" -ne 200 ]; then
            echo "Failed snapshot creation: $status"
            exit 1
          fi
          echo "Snapshots created."
